Start the move to make

diff --git a/firmwarepackager b/firmwarepackager
--- a/firmwarepackager
+++ b/firmwarepackager
@@ -1,141 +1,128 @@
 #!/bin/bash
 
-function splash() {
-clear
-cat << "EOF"
-
-  ___ _            _         _       
- / __| |_ __ _ _ _| |   __ _| |__ ___
- \__ |  _/ _` | '_| |__/ _` | '_ (_-<
- |___/\__\__,_|_| |____\__,_|_.__/__/
-
-EOF
-echo "============================================================================"
-echo "$1"
-echo "============================================================================"
-}
-
 date=$(date '+%Y-%m-%d')
 
-splash "Which laptop are you creating an update for?"
-PS3="Select the model: "
+model=$(dialog --no-tags --radiolist "Select the model:" 60 75 25 \
+	"StarLite MkII"		"StarLite Mk II"	on \
+	"StarLite MkIII"	"StarLite Mk III"	off \
+	"StarLite MkIV"		"StarLite Mk IV"	off \
+	"StarLabTop MkIII"	"StarLabTop Mk III"	off \
+	"StarLabTop MkIV"	"StarLabTop Mk IV"	off \
+	"StarBook MkV"		"StarBook Mk V"		off \
+	"StarBook MkV-Intel"	"StarBook Mk V - Intel"	off \
+	"StarBook MkV-AMD"	"StarBook Mk V - AMD"	off \
+	"Byte MkI"		"Byte Mk I"		off \
+	 --output-fd 1)
 
-models=("StarLite MkII" "StarLite MkIII" "StarLite MkIV" "StarLabTop MkIII" "StarLabTop MkIV" "StarBook MkV" "StarBook MkVI-Intel" "StarBook MkVI-AMD" "Byte MkI-AMD")
-select model in "${models[@]}"
-do
-	case $model in
-		"StarLite MkII")
-			ref="I2"
-			shell="/P /N"
-			hwid="80f1fd54-f581-571f-90e6-00bf8a67f627"
-			uefi="797f8bae-0ea2-4c0f-8a30-7d10ccfacbc0"
-			superio="0aa07091-dc02-5e62-a0cd-9d3880721b64"
-			superio2="f90a3e8e-af9b-5023-8804-a7faf809e0b1"
-			ami="0676539d-150f-5f07-89b9-fe0afd98c44e"
-			break
-			;;
-		"StarLite MkIII")
-			ref="I3"
-			shell="/P /N"
-			hwid="d5521faa-c50b-5d64-971d-8fd400030c51"
-			uefi="d9d7b13b-e4db-4f91-8bf6-8952a9caa82a"
-			superio="0aa07091-dc02-5e62-a0cd-9d3880721b64"
-			superio2="b0e3a8ac-24ce-55e3-8aad-2261f1f4fa08"
-			ami="ec375a72-9ed9-5a21-b1da-5e7f00dcada1"
-			coreboot="3d2f164a-8818-58fd-a082-6c60a67e21a6"
-			break
-			;;
-		"StarLite MkIV")
-			ref="I4"
-			shell="/P /N"
-			hwid="0fc25c8c-ffa8-54ad-a216-d13cfe75bee4"
-			uefi="b1ff7b4d-8b6a-4f50-a047-cddfdb75fa28"
-			ami="32edd806-13a0-5b0f-a8e9-656a0e147369"
-			coreboot="5dc1dd5b-761e-5146-8ac2-1fdd8445f2ff"
-			break
-			;;
-		"StarLabTop MkIII")
-			ref="L3"
-			shell="/P /N /B /L"
-			hwid="013b60e5-1023-5bee-8ae5-14cae21377b7"	# AMI HWID
-			hwid2="8f8ca82b-30e1-5907-bc9d-4257a49898d4"	# coreboot HWID
-			uefi="8265d473-a6c2-42b4-897b-bc220faa2d32"
-			superio="0aa07091-dc02-5e62-a0cd-9d3880721b64"
-			superio2="f90a3e8e-af9b-5023-8804-a7faf809e0b1"
-			ami="a20caf4c-3ed8-531c-b59a-eb079ab5e65e"
-			coreboot="d33219e2-b84c-53a8-a624-27af9752dba6"
-			break
-			;;
-		"StarLabTop MkIV")
-			ref="L4"
-			shell="/P /N /B /L"
-			hwid="baf1d04e-fd16-5e6a-93cc-1c23d171f879"
-			uefi="502bff68-b8db-4b01-86ef-ab65f6502a77"
-			superio="0aa07091-dc02-5e62-a0cd-9d3880721b64"
-			superio2="1e8bc0cc-eee2-5e30-ab4f-1ff923118f01"
-			ami="cc6437bf-0955-5c03-84a6-8b87c7a7c244"
-			coreboot="0ee5867c-93f0-5fb4-adf1-9d686ea1183a"
-			break
-			;;
-		"StarBook MkV")
-			ref="B5"
-			shell="/P /N /B /L"
-			hwid="85aba599-addd-5985-a2e8-eddb41c61ba3"
-			uefi="e27d9e98-cbb2-4975-a8f8-261de2adde05"
-			superio="d83a4cd0-fce6-58a8-93c7-bcee89b41dcf"
-			superio2="049060b5-5010-5ca0-8002-07923951d15e"
-			ami="612d0af2-6b4b-5d1a-bd63-433022fdaefe"
-			coreboot="54c96fef-31e7-5011-a3ff-ea8e855d9acd"
-			break
-			;;
-		"StarBook MkVI-Intel")
-			ref="B6-I"
-			shell="/P /N /B /L"
-			hwid="5c917039-d938-5c9a-b22a-9c392b1534f3"
-			uefi="02e64049-abcc-44a5-af9a-fafc390dd844"
-			superio="d83a4cd0-fce6-58a8-93c7-bcee89b41dcf"
-			superio2=""
-			ami="1292e166-a66f-5e11-b2bb-53265a8f53d9"
-			coreboot="8c994a92-7ef8-5d68-80b5-99ead7cf4686"
-			break
-			;;
-		"StarBook MkVI-AMD")
-			ref="B6-A"
-			shell="/P /B /N /R /K /X /L"
-			hwid="b39593ad-7522-52a5-a4ab-1b2ca2153956"
-			uefi="5a29ddbb-11dd-476d-a641-a45c1db63d5c"
-			superio="d83a4cd0-fce6-58a8-93c7-bcee89b41dcf"
-			superio2=""
-			ami="4c7c8bc5-475c-5384-b602-78c9d4771b5d"
-			coreboot=""
-			break
-			;;
-		"Byte MkI")
-			ref="Y1"
-			shell="/P /B /N /R /K /X /L"
-			hwid="79a64046-5643-59c4-91d0-e68b33db5829"
-			uefi="c24f6311-d2de-49e6-aba0-b8e971b1a425"
-			superio="d83a4cd0-fce6-58a8-93c7-bcee89b41dcf"
-			superio2=""
-			ami=""
-			coreboot=""
-			break
-			;;
-	esac
-done
+# Defaults for newer models
+tool="ifu"
+switch="128"
+
+case $model in
+"StarLite MkII")
+	ref="I2"
+	shell="/P /N"
+	hwid="80f1fd54-f581-571f-90e6-00bf8a67f627"
+	uefi="797f8bae-0ea2-4c0f-8a30-7d10ccfacbc0"
+	superio="0aa07091-dc02-5e62-a0cd-9d3880721b64"
+	superio2="f90a3e8e-af9b-5023-8804-a7faf809e0b1"
+	ami="0676539d-150f-5f07-89b9-fe0afd98c44e"
+	tool="eFuitX64"
+	selector=" /u"
+	switch="/faildelay"
+"StarLite MkIII")
+	ref="I3"
+	shell="/P /N"
+	hwid="d5521faa-c50b-5d64-971d-8fd400030c51"
+	uefi="d9d7b13b-e4db-4f91-8bf6-8952a9caa82a"
+	superio="0aa07091-dc02-5e62-a0cd-9d3880721b64"
+	superio2="b0e3a8ac-24ce-55e3-8aad-2261f1f4fa08"
+	ami="ec375a72-9ed9-5a21-b1da-5e7f00dcada1"
+	coreboot="3d2f164a-8818-58fd-a082-6c60a67e21a6"
+	tool="eFuitX64"
+	selector=" /u"
+	switch="/faildelay"
+"StarLite MkIV")
+	ref="I4"
+	shell="/P /N"
+	hwid="0fc25c8c-ffa8-54ad-a216-d13cfe75bee4"
+	uefi="b1ff7b4d-8b6a-4f50-a047-cddfdb75fa28"
+	ami="32edd806-13a0-5b0f-a8e9-656a0e147369"
+	coreboot="5dc1dd5b-761e-5146-8ac2-1fdd8445f2ff"
+"StarLabTop MkIII")
+	ref="L3"
+	shell="/P /N /B /L"
+	hwid="013b60e5-1023-5bee-8ae5-14cae21377b7"
+	hwid2="8f8ca82b-30e1-5907-bc9d-4257a49898d4"
+	uefi="8265d473-a6c2-42b4-897b-bc220faa2d32"
+	superio="0aa07091-dc02-5e62-a0cd-9d3880721b64"
+	superio2="f90a3e8e-af9b-5023-8804-a7faf809e0b1"
+	ami="a20caf4c-3ed8-531c-b59a-eb079ab5e65e"
+	coreboot="d33219e2-b84c-53a8-a624-27af9752dba6"
+	tool="eFuitX64"
+	selector=" /u"
+	switch="/faildelay"
+"StarLabTop MkIV")
+	ref="L4"
+	shell="/P /N /B /L"
+	hwid="baf1d04e-fd16-5e6a-93cc-1c23d171f879"
+	uefi="502bff68-b8db-4b01-86ef-ab65f6502a77"
+	superio="0aa07091-dc02-5e62-a0cd-9d3880721b64"
+	superio2="1e8bc0cc-eee2-5e30-ab4f-1ff923118f01"
+	ami="cc6437bf-0955-5c03-84a6-8b87c7a7c244"
+	coreboot="0ee5867c-93f0-5fb4-adf1-9d686ea1183a"
+	tool="eFuitX64"
+	selector=" /u"
+	switch="/faildelay"
+"StarBook MkV")
+	ref="B5"
+	shell="/P /N /B /L"
+	hwid="85aba599-addd-5985-a2e8-eddb41c61ba3"
+	uefi="e27d9e98-cbb2-4975-a8f8-261de2adde05"
+	superio="d83a4cd0-fce6-58a8-93c7-bcee89b41dcf"
+	superio2="049060b5-5010-5ca0-8002-07923951d15e"
+	ami="612d0af2-6b4b-5d1a-bd63-433022fdaefe"
+	coreboot="54c96fef-31e7-5011-a3ff-ea8e855d9acd"
+"StarBook MkVI-Intel")
+	ref="B6-I"
+	shell="/P /N /B /L"
+	hwid="5c917039-d938-5c9a-b22a-9c392b1534f3"
+	uefi="02e64049-abcc-44a5-af9a-fafc390dd844"
+	superio="d83a4cd0-fce6-58a8-93c7-bcee89b41dcf"
+	ami="1292e166-a66f-5e11-b2bb-53265a8f53d9"
+	coreboot="8c994a92-7ef8-5d68-80b5-99ead7cf4686"
+"StarBook MkVI-AMD")
+	ref="B6-A"
+	shell="/P /B /N /R /K /X /L"
+	hwid="b39593ad-7522-52a5-a4ab-1b2ca2153956"
+	uefi="5a29ddbb-11dd-476d-a641-a45c1db63d5c"
+	superio="d83a4cd0-fce6-58a8-93c7-bcee89b41dcf"
+	ami="4c7c8bc5-475c-5384-b602-78c9d4771b5d"
+	coreboot=""
+"Byte MkI")
+	ref="Y1"
+	shell="/P /B /N /R /K /X /L"
+	hwid="79a64046-5643-59c4-91d0-e68b33db5829"
+	uefi="c24f6311-d2de-49e6-aba0-b8e971b1a425"
+	superio="d83a4cd0-fce6-58a8-93c7-bcee89b41dcf"
+	ami=""
+	coreboot=""
+esac
 
 series=`echo $model | cut -d ' ' -f1`
 ver=`echo $model | cut -d ' ' -f2`
 
-splash "What is the version number"
-PS3="Select the version: "
 version=$(ls | grep '.rom\|.bin' | sed 's/.rom//g' | sed 's/.bin//g' | uniq)
 
-if [[ -e "$version.rom" ]] && [[ -e "$version.bin" ]]; then
-	:
-elif [[ -e "$version.rom" ]] && [[ $(du -k "$version.rom" | cut -f1) = 8*** ]]; then
-	# 8192KB SPI, no dedicated binary
-	cp $version.rom $version.bin
+# if [[ -e "$version.rom" ]] && [[ -e "$version.bin" ]]; then
+#	:
+#elif [[ -e "$version.rom" ]] && [[ $(du -k "$version.rom" | cut -f1) = 8*** ]]; then
+#	# 8192KB SPI, no dedicated binary
+#	cp $version.rom $version.bin
+#fi
+
+if [[ ! -e "$version".bin ]]; then
+	cp "$version".rom "$version".bin
 fi
 
 releasenotes=()
@@ -226,137 +213,93 @@ printf "echo -off \
 	\nendfor" >> startup.nsh
 }
 
-splash "Which type of update is it?"
-PS3="Select the firmware: "
-firmwares=("AMI" "coreboot" "ITE" "ITE128")
-select firmware in "${firmwares[@]}"
-do
-	target=$(echo "$series/$ver/$firmware/$version")
-	mkdir -p "$target"
-	cp $version.* "$target/"
+model=$(dialog --no-tags --radiolist "Select the firmware type:" 60 75 25 \
+	"AMI"		"AMI"		on \
+	"coreboot"	"coreboot"	off \
+	"ITE"		"ITE"		off \
+         --output-fd 1)
 
-	case $firmware in
-		"AMI")
-			if [[ ! -e "$version.rom" ]] && [[ ! -e "$version.bin" ]]; then
-				echo "Required files not found. $version.rom $version.bin"
-				exit 0
-			fi
-			# CAB: UEFI Capsule
-			ClientVersion="1.3.9"
-			UpdateProtocol="org.uefi.capsule"
-			if [[ "$ref" == "B5" ]]; then
-				VersionFormat="number"
-			else
-				VersionFormat="triplet"
-			fi
-			PrimaryGuid="$uefi"
-			Extension="cap"
-			metadata
-			./header.py --guid "$uefi" --bin "$version.rom" --cap "$version.cap"
-			gcab -c "$target/uefi-$ref.cab" "$version.cap" "$ref.metainfo.xml"
-			rm "$ref.metainfo.xml" "$version.cap" "$version.rom"
-			# CAB: flashrom
-			ClientVersion="1.7.0"
-			UpdateProtocol="org.flashrom"
-			if [[ "$ref" == "B5" ]]; then
-				VersionFormat="number"
-			else
-				VersionFormat="triplet"
-                        fi
-			Extension="bin"
-			PrimaryGuid="$coreboot"
-			metadata
-			gcab -c "$target/flashrom-$ref.cab" "$version.bin" "$ref.metainfo.xml"
-			rm "$ref.metainfo.xml"
-			# EFI Shell Update
-			tool=AfuEfix64
-			switch="$shell"
-			nsh
-			zip -rj "$target/efi-$ref.zip" "$version.bin" "startup.nsh" "binaries/$tool.efi"
-			rm startup.nsh "$version.bin"
-			break
-			;;
-		"coreboot")
-			ClientVersion="1.7.6"
-			UpdateProtocol="org.flashrom"
-			VersionFormat="pair"
-			Branch="<branch>$firmware</branch>"
-			Client="<client>switch-branch</client>"
-			Base=""
-			PrimaryGuid="$coreboot"
-			SecondaryGuid="$ami"
-			Extension="rom"
-			metadata
-			gcab -c "$target/coreboot-$ref.cab" "$version.rom" "$ref.metainfo.xml"
-			rm "$ref.metainfo.xml" "$version.rom" "$version.bin"
-			break
-			;;
-		"ITE")
-			# CAB
-			ClientVersion="1.7.0"
-			UpdateProtocol="tw.com.ite.superio"
-			VersionFormat="pair"
-			Extension="bin"
-			PrimaryGuid=$superio
-			SecondaryGuid=$superio2
-			metadata
-			gcab -c "$target/ite-$ref.cab" "$version.bin" "$ref.metainfo.xml"
-			rm "$ref.metainfo.xml"
-			# EFI Shell Update
-			tool="eFuitX64"
-			selector=" /u"
-			switch="/faildelay"
-			nsh
-			zip -rj "$target/efi-$ref.zip" "$version.bin" "startup.nsh" "binaries/$tool.efi"
-			rm startup.nsh "$version.bin"
-			break
-			;;
-		"ITE128")
-			# CAB
-			ClientVersion="1.7.0"
-			UpdateProtocol="tw.com.ite.superio"
-			VersionFormat="pair"
-			Extension="bin"
-			PrimaryGuid=$superio
-			metadata
-			gcab -c "$target/ite-$ref.cab" "$version.bin" "$ref.metainfo.xml"
-			rm "$ref.metainfo.xml"
-			# EFI Shell Update
-			tool="ifu"
-			selector=""
-			switch="128"
-			nsh
-			zip -rj "$target/efi-$ref.zip" "$version.bin" "startup.nsh" "binaries/$tool.efi"
-			rm startup.nsh "$version.bin"
-			break
-			;;
-	esac
-done
+target=$(echo "$series/$ver/$firmware/$version")
+mkdir -p "$target"
+cp $version.* "$target/"
 
-
-
-echo "Updating README"
+case $firmware in
+"AMI")
+	if [[ ! -e "$version.rom" ]] && [[ ! -e "$version.bin" ]]; then
+		echo "Required files not found. $version.rom $version.bin"
+		exit 0
+	fi
+	# CAB: UEFI Capsule
+	ClientVersion="1.3.9"
+	UpdateProtocol="org.uefi.capsule"
+	VersionFormat="triplet"
+	PrimaryGuid="$uefi"
+	Extension="cap"
+	metadata
+	./header.py --guid "$uefi" --bin "$version.rom" --cap "$version.cap"
+	gcab -c "$target/uefi-$ref.cab" "$version.cap" "$ref.metainfo.xml"
+	rm "$ref.metainfo.xml" "$version.cap" "$version.rom"
+	# CAB: flashrom
+	ClientVersion="1.7.0"
+	UpdateProtocol="org.flashrom"
+	VersionFormat="triplet"
+	Extension="bin"
+	PrimaryGuid="$coreboot"
+	metadata
+	gcab -c "$target/flashrom-$ref.cab" "$version.bin" "$ref.metainfo.xml"
+	rm "$ref.metainfo.xml"
+	# EFI Shell Update
+	tool=AfuEfix64
+	switch="$shell"
+	nsh
+	zip -rj "$target/efi-$ref.zip" "$version.bin" "startup.nsh" "binaries/$tool.efi"
+	rm startup.nsh "$version.bin"
+"coreboot")
+	ClientVersion="1.7.6"
+	UpdateProtocol="org.flashrom"
+	VersionFormat="pair"
+	Branch="<branch>$firmware</branch>"
+	Client="<client>switch-branch</client>"
+	Base=""
+	PrimaryGuid="$coreboot"
+	SecondaryGuid="$ami"
+	Extension="rom"
+	metadata
+	gcab -c "$target/coreboot-$ref.cab" "$version.rom" "$ref.metainfo.xml"
+	rm "$ref.metainfo.xml" "$version.rom" "$version.bin"
+"ITE")
+	# CAB
+	ClientVersion="1.7.0"
+	UpdateProtocol="tw.com.ite.superio"
+	VersionFormat="pair"
+	Extension="bin"
+	PrimaryGuid=$superio
+	SecondaryGuid=$superio2
+	metadata
+	gcab -c "$target/ite-$ref.cab" "$version.bin" "$ref.metainfo.xml"
+	rm "$ref.metainfo.xml"
+	# EFI Shell Update
+	nsh
+	zip -rj "$target/efi-$ref.zip" "$version.bin" "startup.nsh" "binaries/$tool.efi"
+	rm startup.nsh "$version.bin"
+esac
 
 log=`echo "\*\*$series\*\*\[$ver\]"`
-echo $log
 
 sed -i "/$log/a $rn" README.md
 sed -i "/$log/a \#\#\#\# $firmware: [$version](https://github.com/StarLabsLtd/firmware/raw/master/$series/$ver/$firmware/$version/efi-$ref.zip) ($date)" README.md
 
-echo "Upload to GitHub?"
-select git in "Yes" "No"
-do
-	case $git in
-		"Yes")
-			git add *
-			git commit -m "Added $series $ver $firmware $version"
-			git push
-			echo "Done"
-			break
-			;;
-		"No")
-			echo "Done"
-			break
-			;;
-	esac
-done
+dialog --title "Upload" \
+--backtitle "$series $ver $firmware $version" \
+--yesno "Upload to GitHub" 7 60
+
+git=$?
+case $git in
+	"Yes")
+	git add *
+	git commit -m "Added $series $ver $firmware $version"
+	git push
+	echo "Done"
+"No")
+	echo "Done"
+esac
